version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres_smartcity
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
